### ISSUE TITLE
Day of week

### ISSUE THREAD

**Issue by wadem117** [dsi-principles-prog/midterm-wadem117#1]
This dataset provides the date of each game, but not the day of the week. There is a possibility that hockey games are affected by the day of the week that they fall on. 

Create a function that adds and populates a "day_of_week" column.

**Comment by shaswat01** [comment]
You want day_of_week column to be filled with 0,1,.... where 0 means Sunday or with labels, ie with Sun, Mon ,...... ???

**Comment by shaswat01** [comment]
added day_of_week feature, closes #1
